[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Remove conflicting redirects since we have actual /docs routes
# [[redirects]]
#   from = "/docs/*"
#   to = "/"
#   status = 301

[context.production]
  command = "npm install && npm run build"

[context.deploy-preview]
  command = "npm install && npm run build"

[context.branch-deploy]
  command = "npm install && npm run build"